name: Deployment Practise 1
on: push
jobs:
    deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."